name: Build, Test, and Push Docker Image

on:
  push:
    branches:
      - '**' # Run tests on all branches
    tags:
      - '*'  # Run tests and push Docker image on tag

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Set up .NET
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x
      
      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore
      
      # Run tests
      - name: Run tests
        run: dotnet test --configuration Release --no-build --verbosity normal
      
      # Log in to Docker Hub (only for tags)
      - name: Log in to Docker Hub
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      # Build the Docker image (only for tags)
      - name: Build Docker image
        if: startsWith(github.ref, 'refs/tags/')
        run: docker build -t dotanr/web_scraper:${{ github.ref_name }} .
      
      # Push the Docker image (only for tags)
      - name: Push Docker image
        if: startsWith(github.ref, 'refs/tags/')
        run: docker push dotanr/web_scraper:${{ github.ref_name }}