name: Build and Push Docker Image on Tag

on:
  push:
    tags:
      - '*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build the Docker image with the tag
    - name: Build Docker image
      run: docker build -t dotanr/web_scraper:${{ github.ref_name }} .

    # Push the Docker image with the tag
    - name: Push Docker image
      run: docker push dotanr/web_scraper:${{ github.ref_name }}
